server:
  port: 8080
spring:
  application:
    #应用的名称，可选
    name: pytorch-model
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/pytorch-model?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 123456
  servlet:
      # upload file
        multipart:
          max-file-size: 50MB #单个上传文件的最大大小
          max-request-size: 50MB #整个请求的大小不能超过 50 兆字节（MB）
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
#      原始文件上传，这里改为类路径下的文件夹
image:
  upload: C:/Users/Lenovo/Desktop/photo-recognize-project/springboot-pytorch-backend/src/main/resources/static/upload/
#  识别后的文件存放路径
  recognize: C:/Users/Lenovo/Desktop/photo-recognize-project/springboot-pytorch-backend/src/main/resources/static/recognize/
#  模型文件路径
model:
  path: C:/Users/Lenovo/Desktop/photo-recognize-project/springboot-pytorch-backend/src/main/resources/static/model/yolov8n.onnx




